### ISSUE TITLE
A problem when installing an extension to dir with spaces

### ISSUE THREAD

**Issue by spawnnnnn** [jasonterando/vscode-php-tdd#5]
Problem in file 
php-file-parser-service.js
on line 82 - directory with spaces is not working

fix: 
args.push('"' + path.join(path.dirname(__dirname), 'dump.php') + '"');

**Comment by jasonterando** [comment]
Thanks!  I've implemented the fix and published the update (version 0.0.7).  Sorry it took so long, had to blow the dust off of the project.
